version: "3"

services:
 phpapache:
    image: php:8.0.0-apache
    volumes:
      - "./src/:/var/www/html"

 mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=mysqldb
      - MYSQL_ROOT_PASSWORD=oui
    volumes:
      - "./sql/:/docker-entrypoint-initdb.d"

 phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=oui

 nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./ca_maison/www.supersite.com.crt:/etc/ssl/certs/www.supersite.com.crt"
      - "./ca_maison/www.supersite.com.key:/etc/ssl/certs/www.supersite.com.key"
      - "./nginx.conf:/etc/nginx/nginx.conf"
      
volumes:
  db_data:
