vms = [
  { name: "node1.tp3.b2", ip: "10.3.1.11" },
  { name: "node2.tp3.b2", ip: "10.3.1.12" },
  { name: "node3.tp3.b2", ip: "10.3.1.13" }
]

Vagrant.configure("2") do |config|
  
  config.vm.box = "super_box"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  vms.each do |vm|
    config.vm.define vm[:name] do |node|
      node.vm.hostname = vm[:name]
      node.vm.network "private_network", ip: vm[:ip]
    end
  end
end